
= Weforward Gateway

Weforward Gateway 是一个API网关，支持服务注册与发现、访问凭证管理、服务权限管理、服务流量管理。

== 服务注册

使用weforward-framework构建项目，或者参考网关API `__wf_service_register` 接口文档。

== 访问凭证管理

访问凭证分为3种：服务凭证、用户凭证、网关凭证

=== 服务凭证

用于服务注册与调用其他服务，由运维人员通过 `devops` 后台页面或者控制台工具 `console.jar` 维护。

通过控制台工具创建示例：

[source]
----
acc -A --kind H --group default --summary summary
----

分组管理：

上面示例中 `default` 是一个分组名，可根据运维需求建立不同分组，采用多个分组可以更灵活地管理服务权限。

=== 用户凭证

用于用户调用服务，由业务服务维护。

=== 网关凭证

用于网关之间通信与网关调用服务，由网关内部维护。

== 服务权限管理

每个服务需要单独配置权限规则表， 由运维人员通过 `devops` 后台页面或者控制台工具 `console.jar` 维护。

规则项描述了微服务对调用方Access的访问控制，默认（未配置规则时）禁止所有访问。 

- 规则项的名称与描述是给人看的；
- Access支持按id、kind、group匹配，若为空，表示匹配任意Access。
- 依次按规则项的顺序匹配，匹配成功则忽略后面的规则项，根据匹配项的策略决定是否允许访问

示例：

`user` 服务可以任意访问：

[source]
----
rt -A --name user --allow true
----

`pay` 服务只允许 `default` 组的服务访问：

[source]
----
rt -A --name pay --group default --allow true
----

`order` 服务允许用户登录后访问，以及服务间访问：

[source]
----
rt -A --name order --kind US --allow true
rt -A --name order --kind H --allow true
----

== 服务流量管理

每个服务需要单独配置流量规则表，规则表描述微服务实例的流量规则（负载均衡与熔断保护）。 

根据微服务实例的编号与版本号，依次按规则项的顺序匹配，无匹配规则时，相当于屏蔽某实例的流量。 

- 负载均衡： +
采用加权轮询(WRR)的方式， 初始状态（未配置任何规则）为轮询(RR)。

- 熔断保护： +
1.设置微服务示例的最大并发数。当并发数超过最大值，将不再将请求交给此实例。 +
2.设置最大连续失败次数与达到次数后的重置时间。当实例的失败次数达到最大值，在重置时间内，将不再将请求交给此实例。 +
特殊情况，当全部实例的失败次数都达到最大值，将马上重置全部实例。

- 请求转发： +
当网关访问一个微服务实例失败时，默认不会将请求交给其他实例，若要实现类似功能，请参考微服务请求转发。

配置方法：

	请阅读 `devops` 后台页面的帮助信息，或者使用控制台工具 `help traffic`查看帮助
